### ISSUE TITLE
center_scores in pred_square seems to scalar values.

### ISSUE THREAD

**Issue by whwnsdlr1** [navervision/mlsd#18]
HI. I have a question in the code of the pred_squares function. [this line](https://github.com/navervision/mlsd/blob/53a0161d3ecefdd852e6200e2ff8725b7379f3cf/utils.py#L465)
Since center_scores is a scalar value, it seems to be added by just broading casting when calculating score_array.
I wonder if this is intended or if "axis=1" is missing.

**Comment by geonm** [comment]
Sorry for the late reply. I was on vacation.

Yes. This was intended.

`center_scores` is used for finding a rectangle lying in the center of the image.

I simply designed `center_scores` as a value for how far the center points of the square are from the center point of the image.

`square_centers` are the center points of all detected rectangles and `centers` (should be center 😄 ) is the center of the image.

As shown in https://github.com/navervision/mlsd/blob/53a0161d3ecefdd852e6200e2ff8725b7379f3cf/utils.py#L461-L466, this was intended.

**Comment by geonm** [comment]
@whwnsdlr1

Thanks for your comment.

Yes, you are right.

The line 466 https://github.com/navervision/mlsd/blob/53a0161d3ecefdd852e6200e2ff8725b7379f3cf/utils.py#L465 should be modified to follow above my comment.

I will fix it. Thank you again.

**Comment by geonm** [comment]
It is fixed https://github.com/navervision/mlsd/pull/22.

Thanks!
