### ISSUE TITLE
input shape

### ISSUE THREAD

**Issue by spacewalk01** [navervision/mlsd#26]
Would you please explain why input channel of your tflite model is 4?  
`shape of input : [1,512,512,4]`

**Comment by geonm** [comment]
Hi

Please refer to https://github.com/navervision/mlsd#line-segment--box-detection-demo and here https://www.tensorflow.org/lite/performance/gpu#optimizing_for_gpus

MLSD was trained with RGB images (3 channels) but we added an alpha channel so it appears 4 channels as input.

If you want to check how to convert the trained MLSD models from 3 to 4 channels, please refer to https://github.com/navervision/mlsd/blob/master/frozen_models.py#L78

**Comment by spacewalk01** [comment]
Thank you for your quick response!
