### ISSUE TITLE
error for begin web ui

### ISSUE THREAD

**Issue by johnfelipe** [navervision/mlsd#6]
apt update
    apt upgrade
    shutdown -r now

then

    apt install python3-pip
    pip install gradio
    git clone https://github.com/AK391/mlsd.git
    cd mlsd
    pip install -r requirements.txt

this show me cmd

    Requirement already satisfied: numpy in /usr/local/lib/python3.8/dist-packages (from -r requirements.txt (line 1)) (1.20.3)
    Collecting opencv-python
      Downloading opencv_python-4.5.2.54-cp38-cp38-manylinux2014_x86_64.whl (51.0 MB)
         |████████████████████████████████| 51.0 MB 21.0 MB/s
    Requirement already satisfied: pillow in /usr/local/lib/python3.8/dist-packages (from -r requirements.txt (line 3)) (8.2.0)
    Collecting tensorflow-gpu
      Downloading tensorflow_gpu-2.5.0-cp38-cp38-manylinux2010_x86_64.whl (454.4 MB)
         |████████████████████████████████| 454.4 MB 272 bytes/s
    Requirement already satisfied: Flask in /usr/local/lib/python3.8/dist-packages (from -r requirements.txt (line 5)) (2.0.1)
    Requirement already satisfied: gradio in /usr/local/lib/python3.8/dist-packages (from -r requirements.txt (line 6)) (2.0.2)
    Collecting tensorboard~=2.5
      Downloading tensorboard-2.5.0-py3-none-any.whl (6.0 MB)
         |████████████████████████████████| 6.0 MB 54.7 MB/s
    Collecting keras-preprocessing~=1.1.2
      Downloading Keras_Preprocessing-1.1.2-py2.py3-none-any.whl (42 kB)
         |████████████████████████████████| 42 kB 3.6 MB/s
    Collecting google-pasta~=0.2
      Downloading google_pasta-0.2.0-py3-none-any.whl (57 kB)
         |████████████████████████████████| 57 kB 15.3 MB/s
    Collecting keras-nightly~=2.5.0.dev
      Downloading keras_nightly-2.5.0.dev2021032900-py2.py3-none-any.whl (1.2 MB)
         |████████████████████████████████| 1.2 MB 69.3 MB/s
    Collecting opt-einsum~=3.3.0
      Downloading opt_einsum-3.3.0-py3-none-any.whl (65 kB)
         |████████████████████████████████| 65 kB 13.3 MB/s
    Collecting gast==0.4.0
      Downloading gast-0.4.0-py3-none-any.whl (9.8 kB)
    Collecting astunparse~=1.6.3
      Downloading astunparse-1.6.3-py2.py3-none-any.whl (12 kB)
    Collecting wrapt~=1.12.1
      Downloading wrapt-1.12.1.tar.gz (27 kB)
    Collecting h5py~=3.1.0
      Downloading h5py-3.1.0-cp38-cp38-manylinux1_x86_64.whl (4.4 MB)
         |████████████████████████████████| 4.4 MB 73.7 MB/s
    Collecting six~=1.15.0
      Downloading six-1.15.0-py2.py3-none-any.whl (10 kB)
    Collecting absl-py~=0.10
      Downloading absl_py-0.12.0-py3-none-any.whl (129 kB)
         |████████████████████████████████| 129 kB 76.3 MB/s
    Collecting wheel~=0.35
      Downloading wheel-0.36.2-py2.py3-none-any.whl (35 kB)
    Collecting grpcio~=1.34.0
      Downloading grpcio-1.34.1-cp38-cp38-manylinux2014_x86_64.whl (4.0 MB)
         |████████████████████████████████| 4.0 MB 73.2 MB/s
    Collecting flatbuffers~=1.12.0
      Downloading flatbuffers-1.12-py2.py3-none-any.whl (15 kB)
    Collecting protobuf>=3.9.2
      Downloading protobuf-3.17.3-cp38-cp38-manylinux_2_5_x86_64.manylinux1_x86_64.whl (1.0 MB)
         |████████████████████████████████| 1.0 MB 71.5 MB/s
    Collecting typing-extensions~=3.7.4
      Downloading typing_extensions-3.7.4.3-py3-none-any.whl (22 kB)
    Collecting termcolor~=1.1.0
      Downloading termcolor-1.1.0.tar.gz (3.9 kB)
    Collecting tensorflow-estimator<2.6.0,>=2.5.0rc0
      Downloading tensorflow_estimator-2.5.0-py2.py3-none-any.whl (462 kB)
         |████████████████████████████████| 462 kB 74.7 MB/s
    Requirement already satisfied: itsdangerous>=2.0 in /usr/local/lib/python3.8/dist-packages (from Flask->-r requirements.txt (line 5)) (2.0.1)
    Requirement already satisfied: Jinja2>=3.0 in /usr/local/lib/python3.8/dist-packages (from Flask->-r requirements.txt (line 5)) (3.0.1)
    Requirement already satisfied: Werkzeug>=2.0 in /usr/local/lib/python3.8/dist-packages (from Flask->-r requirements.txt (line 5)) (2.0.1)
    Requirement already satisfied: click>=7.1.2 in /usr/local/lib/python3.8/dist-packages (from Flask->-r requirements.txt (line 5)) (8.0.1)
    Requirement already satisfied: analytics-python in /usr/local/lib/python3.8/dist-packages (from gradio->-r requirements.txt (line 6)) (1.3.1)
    Requirement already satisfied: pandas in /usr/local/lib/python3.8/dist-packages (from gradio->-r requirements.txt (line 6)) (1.2.4)
    Requirement already satisfied: paramiko in /usr/local/lib/python3.8/dist-packages (from gradio->-r requirements.txt (line 6)) (2.7.2)
    Requirement already satisfied: ffmpy in /usr/local/lib/python3.8/dist-packages (from gradio->-r requirements.txt (line 6)) (0.3.0)
    Requirement already satisfied: flask-cachebuster in /usr/local/lib/python3.8/dist-packages (from gradio->-r requirements.txt (line 6)) (1.0.0)
    Requirement already satisfied: pycryptodome in /usr/local/lib/python3.8/dist-packages (from gradio->-r requirements.txt (line 6)) (3.10.1)
    Requirement already satisfied: scipy in /usr/local/lib/python3.8/dist-packages (from gradio->-r requirements.txt (line 6)) (1.6.3)
    Requirement already satisfied: Flask-Login in /usr/local/lib/python3.8/dist-packages (from gradio->-r requirements.txt (line 6)) (0.5.0)
    Requirement already satisfied: markdown2 in /usr/local/lib/python3.8/dist-packages (from gradio->-r requirements.txt (line 6)) (2.4.0)
    Requirement already satisfied: matplotlib in /usr/local/lib/python3.8/dist-packages (from gradio->-r requirements.txt (line 6)) (3.4.2)
    Requirement already satisfied: requests in /usr/lib/python3/dist-packages (from gradio->-r requirements.txt (line 6)) (2.22.0)
    Requirement already satisfied: Flask-Cors>=3.0.8 in /usr/local/lib/python3.8/dist-packages (from gradio->-r requirements.txt (line 6)) (3.0.10)
    Collecting tensorboard-data-server<0.7.0,>=0.6.0
      Downloading tensorboard_data_server-0.6.1-py3-none-manylinux2010_x86_64.whl (4.9 MB)
         |████████████████████████████████| 4.9 MB 77.6 MB/s
    Collecting tensorboard-plugin-wit>=1.6.0
      Downloading tensorboard_plugin_wit-1.8.0-py3-none-any.whl (781 kB)
         |████████████████████████████████| 781 kB 66.2 MB/s
    Requirement already satisfied: setuptools>=41.0.0 in /usr/lib/python3/dist-packages (from tensorboard~=2.5->tensorflow-gpu->-r requirements.txt (line 4)) (45.2.0)
    Collecting google-auth<2,>=1.6.3
      Downloading google_auth-1.30.2-py2.py3-none-any.whl (146 kB)
         |████████████████████████████████| 146 kB 82.3 MB/s
    Collecting google-auth-oauthlib<0.5,>=0.4.1
      Downloading google_auth_oauthlib-0.4.4-py2.py3-none-any.whl (18 kB)
    Collecting markdown>=2.6.8
      Downloading Markdown-3.3.4-py3-none-any.whl (97 kB)
         |████████████████████████████████| 97 kB 19.9 MB/s
    Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.8/dist-packages (from Jinja2>=3.0->Flask->-r requirements.txt (line 5)) (2.0.1)
    Requirement already satisfied: backoff==1.10.0 in /usr/local/lib/python3.8/dist-packages (from analytics-python->gradio->-r requirements.txt (line 6)) (1.10.0)
    Requirement already satisfied: python-dateutil>2.1 in /usr/local/lib/python3.8/dist-packages (from analytics-python->gradio->-r requirements.txt (line 6)) (2.8.1)
    Requirement already satisfied: monotonic>=1.5 in /usr/local/lib/python3.8/dist-packages (from analytics-python->gradio->-r requirements.txt (line 6)) (1.6)
    Requirement already satisfied: pytz>=2017.3 in /usr/local/lib/python3.8/dist-packages (from pandas->gradio->-r requirements.txt (line 6)) (2021.1)
    Requirement already satisfied: pynacl>=1.0.1 in /usr/lib/python3/dist-packages (from paramiko->gradio->-r requirements.txt (line 6)) (1.3.0)
    Requirement already satisfied: cryptography>=2.5 in /usr/lib/python3/dist-packages (from paramiko->gradio->-r requirements.txt (line 6)) (2.8)
    Requirement already satisfied: bcrypt>=3.1.3 in /usr/local/lib/python3.8/dist-packages (from paramiko->gradio->-r requirements.txt (line 6)) (3.2.0)
    Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.8/dist-packages (from matplotlib->gradio->-r requirements.txt (line 6)) (1.3.1)
    Requirement already satisfied: pyparsing>=2.2.1 in /usr/local/lib/python3.8/dist-packages (from matplotlib->gradio->-r requirements.txt (line 6)) (2.4.7)
    Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.8/dist-packages (from matplotlib->gradio->-r requirements.txt (line 6)) (0.10.0)
    Collecting cachetools<5.0,>=2.0.0
      Downloading cachetools-4.2.2-py3-none-any.whl (11 kB)
    Requirement already satisfied: pyasn1-modules>=0.2.1 in /usr/lib/python3/dist-packages (from google-auth<2,>=1.6.3->tensorboard~=2.5->tensorflow-gpu->-r requirements.txt (line 4)) (0.2.1)
    Collecting rsa<5,>=3.1.4; python_version >= "3.6"
      Downloading rsa-4.7.2-py3-none-any.whl (34 kB)
    Collecting requests-oauthlib>=0.7.0
      Downloading requests_oauthlib-1.3.0-py2.py3-none-any.whl (23 kB)
    Requirement already satisfied: cffi>=1.1 in /usr/local/lib/python3.8/dist-packages (from bcrypt>=3.1.3->paramiko->gradio->-r requirements.txt (line 6)) (1.14.5)
    Requirement already satisfied: pyasn1>=0.1.3 in /usr/lib/python3/dist-packages (from rsa<5,>=3.1.4; python_version >= "3.6"->google-auth<2,>=1.6.3->tensorboard~=2.5->tensorflow-gpu->-r requirements.txt (line 4)) (0.4.2)
    Requirement already satisfied: oauthlib>=3.0.0 in /usr/lib/python3/dist-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib<0.5,>=0.4.1->tensorboard~=2.5->tensorflow-gpu->-r requirements.txt (line 4)) (3.1.0)
    Requirement already satisfied: pycparser in /usr/local/lib/python3.8/dist-packages (from cffi>=1.1->bcrypt>=3.1.3->paramiko->gradio->-r requirements.txt (line 6)) (2.20)
    Building wheels for collected packages: wrapt, termcolor
      Building wheel for wrapt (setup.py) ... done
      Created wheel for wrapt: filename=wrapt-1.12.1-cp38-cp38-linux_x86_64.whl size=78523 sha256=a505b3132066629135da59f1eb98ce9d8345c4c629073f5e2db1312cdaa1c3f0
      Stored in directory: /root/.cache/pip/wheels/5f/fd/9e/b6cf5890494cb8ef0b5eaff72e5d55a70fb56316007d6dfe73
      Building wheel for termcolor (setup.py) ... done
      Created wheel for termcolor: filename=termcolor-1.1.0-py3-none-any.whl size=4830 sha256=04d8a4a005daff5c461eafe0ed769735eae67519d0be0a1aabbd546ad4ed0c1f
      Stored in directory: /root/.cache/pip/wheels/a0/16/9c/5473df82468f958445479c59e784896fa24f4a5fc024b0f501
    Successfully built wrapt termcolor
    ERROR: launchpadlib 1.10.13 requires testresources, which is not installed.
    ERROR: tensorflow-gpu 2.5.0 has requirement numpy~=1.19.2, but you'll have numpy 1.20.3 which is incompatible.
    Installing collected packages: opencv-python, six, grpcio, protobuf, tensorboard-data-server, tensorboard-plugin-wit, absl-py, wheel, cachetools, rsa, google-auth, requests-oauthlib, google-auth-oauthlib, markdown, tensorboard, keras-preprocessing, google-pasta, keras-nightly, opt-einsum, gast, astunparse, wrapt, h5py, flatbuffers, typing-extensions, termcolor, tensorflow-estimator, tensorflow-gpu
      Attempting uninstall: six
        Found existing installation: six 1.14.0
        Not uninstalling six at /usr/lib/python3/dist-packages, outside environment /usr
        Can't uninstall 'six'. No files were found to uninstall.
      Attempting uninstall: wheel
        Found existing installation: wheel 0.34.2
        Not uninstalling wheel at /usr/lib/python3/dist-packages, outside environment /usr
        Can't uninstall 'wheel'. No files were found to uninstall.
      Attempting uninstall: typing-extensions
        Found existing installation: typing-extensions 3.10.0.0
        Uninstalling typing-extensions-3.10.0.0:
          Successfully uninstalled typing-extensions-3.10.0.0
    Successfully installed absl-py-0.12.0 astunparse-1.6.3 cachetools-4.2.2 flatbuffers-1.12 gast-0.4.0 google-auth-1.30.2 google-auth-oauthlib-0.4.4 google-pasta-0.2.0 grpcio-1.34.1 h5py-3.1.0 keras-nightly-2.5.0.dev2021032900 keras-preprocessing-1.1.2 markdown-3.3.4 opencv-python-4.5.2.54 opt-einsum-3.3.0 protobuf-3.17.3 requests-oauthlib-1.3.0 rsa-4.7.2 six-1.15.0 tensorboard-2.5.0 tensorboard-data-server-0.6.1 tensorboard-plugin-wit-1.8.0 tensorflow-estimator-2.5.0 tensorflow-gpu-2.5.0 termcolor-1.1.0 typing-extensions-3.7.4.3 wheel-0.36.2 wrapt-1.12.1

when put this command:
    python3 demo_MLSD.py

    Traceback (most recent call last):
      File "demo_MLSD.py", line 13, in <module>
        import cv2
      File "/usr/local/lib/python3.8/dist-packages/cv2/__init__.py", line 5, in <module>
        from .cv2 import *
    ImportError: libGL.so.1: cannot open shared object file: No such file or directory

im using ubuntu 20 from scratch

pls help me to solve this

**Comment by johnfelipe** [comment]
Anyone?

**Comment by outmanzm** [comment]
> Anyone?

try

```
sudo apt update
sudo apt install libgl1-mesa-glx
```

reference：
```
https://github.com/conda-forge/pygridgen-feedstock/issues/10
```

**Comment by geonm** [comment]
Hi @johnfelipe 

Sorry for the late reply. Did you solve it?

**Comment by johnfelipe** [comment]
Nothing pls help me...

**Comment by geonm** [comment]
@johnfelipe 
```
$ apt-get install libgl1-mesa-glx
```

Does the same problem occur even if you install libgl through the above command?

**Comment by johnfelipe** [comment]
Yes I do it and not working in my IP and default port, how can solved?

**Comment by geonm** [comment]
@johnfelipe 

I want to help you as much as I can.

Could you share an error message?

**Comment by johnfelipe** [comment]
now from scratch all this steps and working

    apt update
    apt upgrade
    shutdown -r now
    apt install python3-pip
    pip install gradio
    sudo apt update
    sudo apt install libgl1-mesa-glx
    git clone https://github.com/AK391/mlsd.git
    cd mlsd
    pip install -r requirements.txt
    python3 demo_MLSD.py

tnks
